CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR NOT NULL,
  email VARCHAR NOT NULL UNIQUE,
  phone VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS sessions (
  id SERIAL PRIMARY KEY,
  name text NOT NULL,
  time text NOT NULL
);

CREATE TABLE IF NOT EXISTS ticket (
    id SERIAL PRIMARY KEY,
    session_id INT NOT NULL UNIQUE REFERENCES sessions(id),
    pos_row INT NOT NULL UNIQUE,
    cell INT NOT NULL UNIQUE,
    user_id INT NOT NULL REFERENCES users(id)
);